trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/raidTimeline.csproj'
    arguments: '-p:PublishProfile=FolderProfile'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  displayName: 'Upload artifact'
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/raidTimeline/publish/
    artifactName: build

