trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  project: '$(Build.SourcesDirectory)\Source\raidTimeline\raidTimeline.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: $(project)
    arguments: '-p:PublishProfile=FolderProfile'

