trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/raidTimeline.csproj'
    arguments: '-p:PublishProfile=FolderProfile'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  displayName: 'Upload artifact'
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/raidTimeline/publish/
    artifactName: build
    
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'danifischer (1)'
    repositoryName: 'raidTimeline'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: '$(System.DefaultWorkingDirectory)/raidTimeline/publish/'
    isDraft: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'

