trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/raidTimeline.csproj'
    arguments: '-p:PublishProfile=FolderProfile'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      ls $(System.DefaultWorkingDirectory)
      
      ls $(System.DefaultWorkingDirectory)/raidTimeline
      
      ls $(System.DefaultWorkingDirectory)/raidTimeline/publish
    errorActionPreference: 'continue'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/raidTimeline/publish/
    artifactName: build
