trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/raidTimeline.csproj'
    arguments: '-p:PublishProfile=FolderProfile''

