trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
     
  - task: DotNetCoreCLI@2
    displayName: 'Publish app'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/raidTimeline.App.csproj'
      arguments: '-o $(System.DefaultWorkingDirectory)/publish/app -r win-x64 -p:PublishSingleFile=true --self-contained -c Release /p:DebugType=None /p:DebugSymbols=false'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishPipelineArtifact@1
    displayName: 'Upload app'
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/publish/app
      artifactName: build

  - task: DotNetCoreCLI@2
    displayName: 'Publish lib'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/raidTimeline.Logic.csproj'
      arguments: '-o $(System.DefaultWorkingDirectory)/publish/lib -c Release /p:DebugType=None /p:DebugSymbols=false'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishPipelineArtifact@1
    displayName: 'Upload lib'
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/publish/lib
      artifactName: build

